# Generated by Django 5.0.6 on 2024-07-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pos_app", "0004_remove_customer_select_car_remove_customer_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="rating",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
