# Generated by Django 5.0.6 on 2024-07-08 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pos_app", "0005_alter_car_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_customer",
        ),
    ]
